### ISSUE TITLE
表的主键不是只能有一个吗？看到你写的一个表可以有多个主键

### ISSUE THREAD

**Issue by itsvse** [neal1991/fullstack-interview#1]
1、数据库的每张表只能有一个主键，不可能有多个主键。

2、所谓的一张表多个主键，我们称之为联合主键。

     注：联合主键：就是用多个字段一起作为一张表的主键。

**Comment by madneal** [comment]
对的 我那里好像有问题 我那个可能是在那里看到的 当时没注意
