### ISSUE TITLE
一些咨询

### ISSUE THREAD

**Issue by frank-lam** [neal1991/fullstack-interview#2]
冒昧啦，从京东评论来的。最近也在考虑准备入一个4k，显示器。一台PC + MBP2018 13。想问问 接上mac的效果怎么样呀，会卡顿嘛？是不是需要一条 typec 转 dp 的线会好一些呢？

明基PD2700U：“当初一直纠结于LG和明基之间，在看了很多评测之后，最后决定还是买明基。 包装非常的简介，和戴尔比简单...” - 京东
https://club.jd.com/repay/100000507211_a9d567f8-1b36-4c07-9649-15c42e766632_1.html

**Comment by madneal** [comment]
。。。。暴露信息了，明基那个效果还可以，不过要买那种dp-typec的直连线，我试了几个转接头，都有一点问题。

**Comment by frank-lam** [comment]
准备入手了，但是有点纠结戴尔U2718Q 和明基 PD2700U @neal1991

**Comment by madneal** [comment]
反正明基还可以，戴尔估计也还可以吧，但如果我选的话，可能还是选明基。

**Comment by frank-lam** [comment]
感觉差别不会太大，谢谢老哥。准备马上拔草了
